"""Block-status taxonomy aggregator. Status codes lie; this is the layer that catches it."""
from __future__ import annotations

from .parse import FetchedPair, FetchedPage
from .schema import BlockStatus

CHALLENGE_BODY_MARKERS = (
    "just a moment",
    "checking your browser",
    "please wait for verification",
    "please wait...",
    "humans only",
    "réservé aux humains",
    "nur für menschen",
    "human verification",
    "security check",
    "bot or not",
    "pardon our interruption",
    "access denied",
    "_wafchallengeid",
    "waforiginalreid",
    "awswafcookiedomainlist",
    "awswafchallenge",
    "challenge-platform",
    "_cf_chl_opt",
    "datadomeclientkey",
    "datadome-container",
    "px-captcha",
    "captcha-pwa",
    "/cdn-cgi/challenge-platform",
    "errors.edgesuite.net",
    "generated by cloudfront",
)

ARMED_PASSIVE_COOKIES = (
    "__cf_bm",
    "_cfuvid",
    "_abck",
    "bm_sz",
    "bm_so",
    "bm_ss",
    "bm_s",
    "datadome",
    "_pxhd",
    "_px3",
    "_pxvid",
    "_pxhd_cf",
    "akavpau_p2",
)


def compute_block_status(pair: FetchedPair) -> tuple[BlockStatus, list[str]]:
    home = pair.home
    robots = pair.robots
    evidence: list[str] = []

    home_failed = home.fetch_error is not None
    robots_ok = robots.status is not None and 200 <= (robots.status or 0) < 400

    if home_failed and robots_ok:
        evidence.append(
            f"homepage fetch failed ({home.fetch_error}); robots.txt reachable -> tls/connection block"
        )
        return BlockStatus.TLS_BLOCK, evidence

    if home_failed:
        evidence.append(f"homepage fetch failed: {home.fetch_error}")
        return BlockStatus.HARD_BLOCK, evidence

    status = home.status or 0
    body_size = home.body_size_bytes
    body_lower = home.body_lower
    title_lower = home.title.lower()

    found_markers = [m for m in CHALLENGE_BODY_MARKERS if m in body_lower or m in title_lower]

    cf_mitigated = home.header("cf-mitigated").lower()
    if cf_mitigated == "challenge":
        evidence.append("cf-mitigated: challenge")
        return BlockStatus.SOFT_CHALLENGE, evidence

    waf_action = home.header("x-amzn-waf-action").lower()
    if waf_action in {"captcha", "challenge", "block"}:
        evidence.append(f"x-amzn-waf-action: {waf_action}")
        return BlockStatus.SOFT_CHALLENGE, evidence

    if status >= 400:
        if found_markers:
            evidence.append(
                f"status {status} with challenge markers: {found_markers[:3]}"
            )
            return BlockStatus.SOFT_CHALLENGE, evidence
        if body_size < 2_000:
            evidence.append(
                f"status {status} with tiny body ({body_size} bytes) -> hard block"
            )
            return BlockStatus.HARD_BLOCK, evidence
        evidence.append(
            f"status {status} with substantive body but no challenge markers -> soft challenge"
        )
        return BlockStatus.SOFT_CHALLENGE, evidence

    # 2xx region
    if status == 202:
        evidence.append("HTTP 202 with body -> AWS WAF JS challenge pattern")
        return BlockStatus.SOFT_CHALLENGE, evidence

    if 200 <= status < 300:
        # Akamai NetStorage cutout: tiny body containing 'reference #'
        if "reference #" in body_lower and body_size < 1_500:
            evidence.append(f"akamai netstorage stub body ({body_size} bytes)")
            return BlockStatus.BODY_LIES, evidence

        if found_markers and body_size < 100_000:
            evidence.append(
                f"2xx with challenge markers in body: {found_markers[:3]} ({body_size} bytes)"
            )
            return BlockStatus.BODY_LIES, evidence

        # Suspiciously small body for an html resource — only flag if there's
        # also no real content signal (title / OG / JSON-LD / microdata / metas).
        ct = home.header("content-type").lower()
        looks_html = "text/html" in ct or "application/xhtml" in ct or not ct
        if looks_html and body_size < 5_000:
            has_content_signal = bool(
                home.title
                or home.has_opengraph
                or home.has_twitter_cards
                or home.json_ld_blocks
                or home.has_microdata
                or home.named_json_islands
                or home.meta_generators
                or len(home.metas) >= 3
                or len(home.script_srcs) >= 3
                or "__next_f.push" in body_lower
                or "window.__" in body_lower
            )
            if not has_content_signal:
                evidence.append(
                    f"2xx html body suspiciously small ({body_size} bytes), no content signals"
                )
                return BlockStatus.BODY_LIES, evidence

        passive = [c for c in home.set_cookie_names if c in ARMED_PASSIVE_COOKIES]
        if passive:
            evidence.append(f"bot-management cookies issued; page rendered: {passive}")
            return BlockStatus.ARMED_PASSIVE, evidence
        return BlockStatus.NONE, evidence

    evidence.append(f"unexpected status {status}")
    return BlockStatus.NONE, evidence
